# 「研究室の話題」の部分
# please DO USE ENGLISH HALF-WIDTH spaces!
awards:
  -
    year: 2022
    text: 杉村和美が共同執筆した『アイデンティティ 時間と関係を生きる』が出版されました。
    url: null
  -
    year: 2022
    text: 岩佐康弘・日原尚吾・杉村和美の研究発表が，中国四国心理学会第77回大会の大会優秀発表賞を受賞しました(2022.2)。
    url: https://cspa.hiroshima-u.ac.jp/award.html
  -
    year: 2021
    text: 杉村和美・日原尚吾の論文がDevelopmental Psychologyに採択されました(2021.11)。
  -
    year: 2021
    text: 日原尚吾が分担執筆した『新・教職課程演習 第8巻 特別活動・生徒指導・キャリア教育』が出版されました。
  -
    year: 2021
    text: 岩佐康弘・杉村和美の論文が，第10回青年心理学会学会賞を受賞しました(2021.10)。
  -
    year: 2021
    text: 日原尚吾・梅村比丘・岩佐康弘・雜賀智子・杉村和美の論文がDevelopmental Psychologyに掲載されました(2021.8)。
    url: https://doi.apa.org/doiLanding?doi=10.1037%2Fdev0001275
  -
    year: 2021
    text: 岩佐康弘・日原尚吾・梅村比丘・杉村和美の論文 がIdentityに掲載されました(2021.7)。
    url: https://www.tandfonline.com/doi/full/10.1080/15283488.2021.1954520
  -
    year: 2021
    text: 杉村和美の論文が Identityに掲載されました(2021.7)。
    url: https://www.tandfonline.com/doi/full/10.1080/15283488.2021.1947819
  -
    year: 2021
    text: 繁田京ノ輔が国際Identity学会 (ISRI) でStudent Research Awardを受賞しました(2021.6)。
  -
    year: 2021
    text: 日原尚吾の研究が，2020年度 小貫英教育賞を受賞しました(2021.5)。
  -
    year: 2021
    text: 梅村比丘・杉村和美の論文が Attachment & Human Developmentに掲載されました(2021.4)。
    url: https://www.tandfonline.com/doi/abs/10.1080/14616734.2021.1881134?journalCode=rahd20
  -
    year: 2021
    text: 日原尚吾・杉村和美・梅村比丘・岩佐康弘の論文が Development and Psychopathology に掲載されました (2021.03)。
    url: https://www.cambridge.org/core/journals/development-and-psychopathology/article/abs/positive-and-negative-valences-of-identities-longitudinal-associations-of-identity-content-valences-with-adaptive-and-maladaptive-functioning-among-japanese-young-adults/F957592F6CEE82FAD1F2DC75A8BD7572
  -
    year: 2021
    text: 梅村比丘の論文が Current Psychologyに掲載されました(2021.01)。
    url: https://link.springer.com/article/10.1007/s12144-020-01297-9
  -
    year: 2021
    text: 梅村比丘の論文が PLoS ONEに掲載されました(2021.01)。
    url: https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0244278
  -
    year: 2020
    text: 梅村比丘の論文が Journal of Early Adolescenceに掲載されました(2020.12)。
    url: https://www.sciencedirect.com/science/article/abs/pii/S092523122020000X
  -
    year: 2020
    text: 杉村和美・岩佐康弘(認知心理学研究室との共同研究) の論文がScientific Reportsに掲載されました(2020.12)。
    url: https://www.nature.com/articles/s41598-020-79444-2
  -
    year: 2020
    text: 日原尚吾・雜賀智子・杉村和美の論文がIdentityに掲載されました(2020.11)。
    url: https://doi.org/10.1080/15283488.2020.1839757
  -
    year: 2020
    text: 梅村比丘がHIRAKU-Global選抜教員に就任しました(2020.10)。
    url: https://www.hiroshima-u.ac.jp/hiraku-g
  -
    year: 2020
    text: 杉村和美・日原尚吾の論文がJournal of Adolescence に掲載されました(2020.09)。
    url: https://www.sciencedirect.com/science/article/pii/S0140197120301408?via%3Dihub
  -
    year: 2020
    text: 杉村和美・日原尚吾の論文がJournal of Social and Personal Relationships に掲載されました(2020.08)。
    url: https://journals.sagepub.com/doi/10.1177/0265407520948621
  -
    year: 2020
    text: 日原尚吾が助教に就任しました(2020.04.01)。
  -
    year: 2020
    text: 岩佐康弘が日本学術振興会特別研究員（DC2）に採用されました (2020.04.01)。
  -
    year: 2019
    text: 杉村和美の論文がJournal of Youth and Adolescenceに採択されました。
    url: https://link.springer.com/article/10.1007/s10964-019-01182-0
  -
    year: 2019
    text: 杉村和美の論文がChild Development Perspectives に採択されました。
    url: https://srcd.onlinelibrary.wiley.com/doi/full/10.1111/cdep.12359
  -
    year: 2019
    text: 梅村比丘が三原市で児童思春期の愛着に関する講演を12月12日に行いました。
    url: https://development.hiroshima-u.ac.jp/ad/20191212_miharakouen.pdf
  -
    year: 2019
    text: 徳岡大が日本パーソナリティ心理学会第28回大会で優秀発表賞を受賞しました。
  -
    year: 2019
    text: 梅村比丘が日本心理学会第83回大会でアタッチメントのシンポジウムを行いました。
    url: https://development.hiroshima-u.ac.jp/rese/Tomotaka_Umemura/Nissinsinpo.pdf
  -
    year: 2019
    text: Masaryk UniversityのDr. Lukas BlinkaとDr. Anna Sevcikovaが講演を行いました。
    url: https://development.hiroshima-u.ac.jp/ad/Addiction%20Research%20Poster.pdf
  -
    year: 2019
    text: 日原尚吾・石橋彩波・梅村比丘・杉村和美の論文がEmerging Adulthoodに掲載されました。
    url: https://journals.sagepub.com/doi/full/10.1177/2167696819858457

# Homepage Image banner.
# Can add as many images as required.
# please DO USE ENGLISH HALF-WIDTH spaces!
bannerImages:
  - images/syugo/sugimuraken_syugo202203.jpeg
  - images/syugo/umemuraken_syugo202203.jpeg
  - images/2019_aki_sinkan.jpeg
  - https://development.hiroshima-u.ac.jp/images/sche/201804shinkan.jpg

graduates:
  -
    year: 2021
    undergrad: 学部生(3名)：大学院進学(2名)，民間企業(1名)
    grad: 院生(4名)：梅光学院大学講師(1名)，大学院進学(1名)，公務員(2名)
  -
    year: 2020
    undergrad: 学部生(3名)：大学院進学(2名)，民間(1名：児童発達支援)
    grad: 院生(1名)：医療機関(1名：一般病院)
  -
    year: 2019
    undergrad: 学部生(2名)：大学院進学(1名)
    grad: 院生(3名)：広島大学助教(1名)，公務員(1名)，公益財団法人(1名)
  -
    year: 2018
    undergrad: 学部生(2名)：民間企業(2名,：製薬，放送)
    grad: 院生(1名)：民間企業(1名：ウェディング)
  -
    year: 2017
    undergrad: 学部生(2名)：大学院進学(2名)
  -
    year: 2016
    undergrad: 学部生(2名)：大学院進学(2名)
  -
    year: 2015
    undergrad: 学部生(2名)：家庭裁判所調査官(1名)，公務員(1名：県警)，民間企業(1名：SE)
    grad: 院生(3名)：博士課程進学(1名)，家庭裁判所調査官(1名)，民間企業(1名：貿易)
  -
    year: 2014
    undergrad: 学部生(3名)：大学院進学(2名)，民間企業(1名：食品)
  -
    year: 2013
    undergrad: 学部生(3名)：大学院進学(2名)，公務員(1名：児童厚生施設)


members:
  -
    name: 杉村 和美
    position: 教授
    image: https://development.hiroshima-u.ac.jp/images/people/Kazumi_Sugimura.jpg
    intro: 東京生まれ、名古屋育ち。教員になってからは愛知学泉女子短期大学、追手門学院大学、名古屋大学、広島大学の４つを経験していますので，多様な背景を持つ学生・院生の指導ができると思います。一緒にアイデンティティの発達を研究したい人は、ぜひ来てください。
    field: アイデンティティ理論，自律，大人への移行，親子関係，仲間関係，文化の中での発達
    others:
      -
        title: 連絡先
        content: <a href="mailto:ksugimura@hiroshima-u.ac.jp">ksugimura@hiroshima-u.ac.jp</a>
      -
        title: 研究者総覧
        content: <a href="https://goo.gl/HG59FA" target="_blank"> https://goo.gl/HG59FA</a>



# Menu items to show in the navigation menu.
# please DO USE ENGLISH HALF-WIDTH spaces!
menuItems:
  -
    name: ホーム
    english: Home
    url: index.html
    show: true
  -
    name: メンバー紹介
    english: Members
    url: members.html
    show: true
  -
    name: 杉村和美の研究活動
    english: Sugimura's activities
    url: research_activity_sugimura.html
    show: true
  -
    name: 梅村比丘の研究活動
    english: Umemura's activities
    url: research_activity_umemura.html
    show: true
  -
    name: 一例
    english: An example
    url: path_to_webpage.html
    show: false
  -
    name: 学生の研究活動
    english: Students' activities
    url: research_activity_students.html
    show: true
  -
    name: 年間スケジュール
    english: Annual schedule
    url: annual_schedule.html
    show: true